spring.application.name=TattooAppointmentService
server.port=8099
spring.datasource.username=${PSQL_USERNAME}
spring.datasource.password=${PSQL_PASSWORD}
spring.datasource.url=jdbc:postgresql://localhost:5433/tattooappointmentservice
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

mail.sender.app.password=${MAIL_SENDER_APP_PASSWORD}
mail.sender.email=${MAIL_SENDER_EMAIL}

spring.servlet.multipart.max-file-size=10MB

azure.openai.key=${AZURE_OPENAI_KEY}
azure.openai.endpoint=${AZURE_OPENAI_ENDPOINT}